"""New Migration

Revision ID: 0ac4ca8250c5
Revises: dec15d6ee471
Create Date: 2022-10-18 19:44:25.525510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac4ca8250c5'
down_revision = 'dec15d6ee471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('cnpj', sa.String(), nullable=True))
    op.drop_constraint('empresa_cpnj_key', 'empresa', type_='unique')
    op.create_unique_constraint(None, 'empresa', ['cnpj'])
    op.drop_column('empresa', 'cpnj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('cpnj', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'empresa', type_='unique')
    op.create_unique_constraint('empresa_cpnj_key', 'empresa', ['cpnj'])
    op.drop_column('empresa', 'cnpj')
    # ### end Alembic commands ###
