"""New Migration

Revision ID: 0c4a3dae80b0
Revises: 0fd05f2fde76
Create Date: 2022-11-30 04:40:45.003520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c4a3dae80b0'
down_revision = '0fd05f2fde76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forgotPassword', 'expired_in')
    op.drop_column('forgotPassword', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forgotPassword', sa.Column('status', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('forgotPassword', sa.Column('expired_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
