"""New Migration

Revision ID: 0fd05f2fde76
Revises: 1a5ad89b5cd5
Create Date: 2022-11-21 04:37:36.971696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd05f2fde76'
down_revision = '1a5ad89b5cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
