"""New Migration

Revision ID: 1a5ad89b5cd5
Revises: 8fcaee555f47
Create Date: 2022-11-21 04:35:17.618229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5ad89b5cd5'
down_revision = '8fcaee555f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
