"""New Migration

Revision ID: 4bf5bc728a97
Revises: 0ac4ca8250c5
Create Date: 2022-11-15 23:57:07.593271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf5bc728a97'
down_revision = '0ac4ca8250c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('empresa_cnpj', sa.String(), nullable=True))
    op.add_column('processo', sa.Column('funcionario_cpf', sa.String(), nullable=True))
    op.drop_constraint('processo_funcionario_id_fkey', 'processo', type_='foreignkey')
    op.drop_constraint('processo_empresa_id_fkey', 'processo', type_='foreignkey')
    op.create_foreign_key(None, 'processo', 'empresa', ['empresa_cnpj'], ['cnpj'])
    op.create_foreign_key(None, 'processo', 'funcionario', ['funcionario_cpf'], ['cpf'])
    op.drop_column('processo', 'empresa_id')
    op.drop_column('processo', 'funcionario_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('processo', sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'processo', type_='foreignkey')
    op.drop_constraint(None, 'processo', type_='foreignkey')
    op.create_foreign_key('processo_empresa_id_fkey', 'processo', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key('processo_funcionario_id_fkey', 'processo', 'funcionario', ['funcionario_id'], ['id'])
    op.drop_column('processo', 'funcionario_cpf')
    op.drop_column('processo', 'empresa_cnpj')
    # ### end Alembic commands ###
