"""New Migration

Revision ID: 8fcaee555f47
Revises: 4bf5bc728a97
Create Date: 2022-11-21 03:51:05.280216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcaee555f47'
down_revision = '4bf5bc728a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forgotPassword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('expired_in', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forgotPassword')
    # ### end Alembic commands ###
